name: SIMD tests

on:
  push:
  pull_request:

jobs:
  sde:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: AVX2
            test: avx2
            feature: avx2-tests
            cross_config: ci/Cross.avx2.toml
          - name: SSE2
            test: sse2
            feature: sse2-tests
            cross_config: ci/Cross.sse2.toml

    name: test ${{ matrix.name }} under Intel SDE

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Install or use cached cross-rs/cross
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cross

      - uses: Swatinem/rust-cache@v2

      - name: Start Docker
        run: sudo systemctl start docker

      - name: Run ${{ matrix.name }} integration test under SDE
        env:
          CROSS_CONFIG: ${{ matrix.cross_config }}
        run: |
          cross test \
            --target x86_64-unknown-linux-gnu \
            --test "${{ matrix.test }}" \
            --features "${{ matrix.feature }}" \
            --verbose \
            -- --nocapture
